"""empty message

Revision ID: 7e8f7f04499a
Revises: c44a8b0a01c6
Create Date: 2024-09-24 14:38:42.933410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8f7f04499a'
down_revision = 'c44a8b0a01c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spin_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_book_id', sa.Integer(), nullable=False),
    sa.Column('spin_off_book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['spin_off_book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spin_off_book_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('types_books_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('book_types_Books_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('book_spin_off_de_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'types_books', ['types_books_id'], ['id'])
        batch_op.drop_column('spin_off_de_id')
        batch_op.drop_column('types_Books_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('types_Books_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('spin_off_de_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_spin_off_de_id_fkey', 'book', ['spin_off_de_id'], ['id'])
        batch_op.create_foreign_key('book_types_Books_id_fkey', 'types_books', ['types_Books_id'], ['id'])
        batch_op.drop_column('types_books_id')

    op.drop_table('spin_off')
    # ### end Alembic commands ###
