"""empty message

<<<<<<<< HEAD:migrations/versions/fac470eea622_.py
Revision ID: fac470eea622
Revises: 
Create Date: 2024-10-15 15:03:31.359052
========
Revision ID: 646aa51d208e
Revises: 
Create Date: 2024-10-15 12:47:16.775805
>>>>>>>> 154e75b8469bc826a8337232fbdbace23a643b00:migrations/versions/646aa51d208e_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/fac470eea622_.py
revision = 'fac470eea622'
========
revision = '646aa51d208e'
>>>>>>>> 154e75b8469bc826a8337232fbdbace23a643b00:migrations/versions/646aa51d208e_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('typebook', sa.String(length=120), nullable=False),
    sa.Column('picture_url', sa.String(length=120), nullable=False),
    sa.Column('synopsis', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author'),
    sa.UniqueConstraint('picture_url'),
    sa.UniqueConstraint('synopsis'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('typebook')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
